/**
 * Reduce ICI expense-ratio data → src/data/generated/fees.ts
 *
 * The data behind "The Real Cost of Fees": the average expense ratio investors
 * actually paid each year, 1996–present, split by active vs. index and equity vs.
 * bond funds. Two stories jump out: fees have fallen dramatically over 30 years,
 * and index funds cost a small fraction of what active funds do. Those real
 * anchors let the tool's fee-drag calculator use figures investors actually face.
 *
 * Source: Investment Company Institute, "Trends in the Expenses and Fees of
 * Funds, 2025" (per32-01), Figure S3 — asset-weighted averages, i.e. what the
 * typical invested dollar actually paid (not a simple average across funds).
 *
 * Governance: ICI raw workbook is git-ignored; only this reduced aggregate ships.
 *
 * Run:  npm run data:fees
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readWorkbook } from "./lib/read-xlsx.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "data", "sources", "ici", "per32-01-data.xlsx");
const OUT = join(root, "src", "data", "generated", "fees.ts");

// Figure S3 columns (0-indexed) — asset-weighted average expense ratios, %.
const SERIES = [
  { id: "active-equity", name: "Actively managed equity", kind: "equity", active: true, col: 1 },
  { id: "index-equity", name: "Index equity", kind: "equity", active: false, col: 4 },
  { id: "active-bond", name: "Actively managed bond", kind: "bond", active: true, col: 7 },
  { id: "index-bond", name: "Index bond", kind: "bond", active: false, col: 10 },
];

function main() {
  const rows = readWorkbook(SRC).sheet("S3");
  // Data rows: first cell is a 4-digit year.
  const dataRows = rows.filter((r) => Number.isInteger(Number(r?.[0])) && Number(r[0]) > 1980 && Number(r[0]) < 2100);

  const series = SERIES.map((s) => ({
    id: s.id,
    name: s.name,
    kind: s.kind,
    active: s.active,
    points: dataRows
      .map((r) => ({ year: Number(r[0]), ratio: Number(r[s.col]) }))
      .filter((p) => Number.isFinite(p.ratio)),
  }));

  const start = Math.max(...series.map((s) => s.points[0].year));
  const end = Math.min(...series.map((s) => s.points[s.points.length - 1].year));
  const latest = (id) => series.find((s) => s.id === id).points.find((p) => p.year === end).ratio;
  const first = (id) => series.find((s) => s.id === id).points.find((p) => p.year === start).ratio;

  const out = {
    asOf: end,
    start,
    end,
    source:
      "Investment Company Institute, “Trends in the Expenses and Fees of Funds, 2025” (Figure S3, asset-weighted averages).",
    // Handy anchors for the tool's real-fee presets.
    latest: {
      activeEquity: latest("active-equity"),
      indexEquity: latest("index-equity"),
      activeBond: latest("active-bond"),
      indexBond: latest("index-bond"),
    },
    series,
  };
  writeFileSync(OUT, render(out));

  console.log(
    `fees: ${series.length} series, ${start}–${end}\n` +
      `  active equity ${first("active-equity")}% (${start}) → ${latest("active-equity")}% (${end})\n` +
      `  index equity  ${first("index-equity")}% (${start}) → ${latest("index-equity")}% (${end})\n` +
      `  today's gap: active ${latest("active-equity")}% vs index ${latest("index-equity")}% equity\n  → ${OUT}`
  );
}

function render(o) {
  const series = o.series
    .map((s) => {
      const pts = s.points.map((p) => `{ year: ${p.year}, ratio: ${p.ratio} }`).join(", ");
      return `  { id: ${JSON.stringify(s.id)}, name: ${JSON.stringify(s.name)}, kind: ${JSON.stringify(s.kind)}, active: ${s.active}, points: [${pts}] },`;
    })
    .join("\n");
  return `// AUTO-GENERATED by scripts/reduce-fees.mjs — DO NOT EDIT.
// Re-run: npm run data:fees
//
// Asset-weighted average expense ratios (%) that fund investors actually paid,
// by year. Source: ICI "Trends in the Expenses and Fees of Funds, 2025."

export interface FeePoint { year: number; ratio: number; }
export interface FeeSeries {
  id: string;
  name: string;
  kind: "equity" | "bond";
  /** True for actively managed funds, false for index funds. */
  active: boolean;
  points: FeePoint[];
}

export interface FeesData {
  asOf: number;
  start: number;
  end: number;
  source: string;
  /** Latest-year asset-weighted expense ratios (%), for real-fee presets. */
  latest: {
    activeEquity: number;
    indexEquity: number;
    activeBond: number;
    indexBond: number;
  };
  series: FeeSeries[];
}

export const fees: FeesData = {
  asOf: ${o.asOf},
  start: ${o.start},
  end: ${o.end},
  source: ${JSON.stringify(o.source)},
  latest: {
    activeEquity: ${o.latest.activeEquity},
    indexEquity: ${o.latest.indexEquity},
    activeBond: ${o.latest.activeBond},
    indexBond: ${o.latest.indexBond},
  },
  series: [
${series}
  ],
};
`;
}

main();
