/**
 * Reduce FRED consumer-borrowing-rate series → src/data/generated/debt.ts
 *
 * The data behind "The Cost of Debt": the interest rate Americans actually pay to
 * borrow. Credit-card APRs are the star — they're the highest-cost, most common
 * consumer debt and the engine of the minimum-payment trap — with auto-loan rates
 * for contrast. Real rates give the tool honest defaults and let us show that a
 * credit card charges more than the stock market has ever reliably returned.
 *
 * Run:  npm run data:debt
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parseFred } from "./lib/parse-fred.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const FRED = join(root, "data", "sources", "fred");
const OUT = join(root, "src", "data", "generated", "debt.ts");

const round = (x, dp) => Math.round(x * 10 ** dp) / 10 ** dp;

/** Monthly rows → { year: annual mean } (years with ≥3 observed months). */
function annualMean(rows) {
  const byYear = new Map();
  for (const r of rows) {
    if (r.value === null) continue;
    const y = +r.date.slice(0, 4);
    if (!byYear.has(y)) byYear.set(y, []);
    byYear.get(y).push(r.value);
  }
  const out = [];
  for (const [year, vals] of [...byYear.entries()].sort((a, b) => a[0] - b[0])) {
    if (vals.length >= 3) out.push({ year, rate: round(vals.reduce((s, v) => s + v, 0) / vals.length, 2) });
  }
  return out;
}

function series(id) {
  const { rows } = parseFred(join(FRED, `${id}.csv`));
  const obs = rows.filter((r) => r.value !== null);
  const latest = obs[obs.length - 1];
  const lo = obs.reduce((a, b) => (b.value < a.value ? b : a));
  const hi = obs.reduce((a, b) => (b.value > a.value ? b : a));
  return {
    latest: latest.value,
    latestDate: latest.date,
    min: lo.value, minYear: +lo.date.slice(0, 4),
    max: hi.value, maxYear: +hi.date.slice(0, 4),
    series: annualMean(rows),
  };
}

function main() {
  const creditCard = series("TERMCBCCALLNS");
  const autoLoan = series("TERMCBAUTO48NS");

  const out = {
    asOf: creditCard.latestDate,
    source:
      "Federal Reserve Board, Commercial Bank Interest Rates (credit card plans; 48-month new-car loans) via FRED.",
    creditCard,
    autoLoan,
  };
  writeFileSync(OUT, render(out));

  console.log(
    `debt: credit card ${creditCard.latest}% (${creditCard.latestDate}); range ${creditCard.min}–${creditCard.max}%\n` +
      `  auto loan ${autoLoan.latest}% (${autoLoan.latestDate})\n  → ${OUT}`
  );
}

function render(o) {
  const s = (x) =>
    `{
    latest: ${x.latest}, latestDate: ${JSON.stringify(x.latestDate)},
    min: ${x.min}, minYear: ${x.minYear}, max: ${x.max}, maxYear: ${x.maxYear},
    series: [${x.series.map((p) => `{ year: ${p.year}, rate: ${p.rate} }`).join(", ")}],
  }`;
  return `// AUTO-GENERATED by scripts/reduce-debt.mjs — DO NOT EDIT.
// Re-run: npm run data:debt
//
// Consumer borrowing rates (%) from the Federal Reserve via FRED. Used for
// realistic APR defaults in the debt tool and to show how costly credit-card
// debt is relative to any return investing can promise.

export interface DebtRatePoint { year: number; rate: number; }
export interface DebtSeries {
  /** Latest observed annual rate (%). */
  latest: number;
  latestDate: string;
  min: number; minYear: number;
  max: number; maxYear: number;
  /** Annual-average rate (%). */
  series: DebtRatePoint[];
}
export interface DebtData {
  asOf: string;
  source: string;
  creditCard: DebtSeries;
  autoLoan: DebtSeries;
}

export const debt: DebtData = {
  asOf: ${JSON.stringify(o.asOf)},
  source: ${JSON.stringify(o.source)},
  creditCard: ${s(o.creditCard)},
  autoLoan: ${s(o.autoLoan)},
};
`;
}

main();
