/**
 * Reduce Shiller's ie_data.xls → src/data/generated/shiller-cape.ts
 *
 * The Cyclically Adjusted Price-to-Earnings ratio (CAPE, or P/E10): the S&P
 * Composite's real price divided by the average of the last 10 years of real
 * earnings. Smoothing earnings over a decade strips out the business cycle, so
 * a high CAPE flags a historically expensive market and a low one a cheap one.
 * Column 12 of the "Data" sheet is Shiller's CAPE; it begins in 1881 (the first
 * month with 10 prior years of earnings).
 *
 * We emit the monthly series plus precomputed summary stats (mean, median,
 * min/max with dates, and where today sits in the full history). Run:
 *   npm run data:cape
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readWorkbook } from "./lib/read-xlsx.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "data", "sources", "shiller", "ie_data.xls");
const OUT = join(root, "src", "data", "generated", "shiller-cape.ts");

const COL_DATE = 0;
const COL_CAPE = 12; // Cyclically Adjusted PE Ratio (P/E10)

function main() {
  const rows = readWorkbook(SRC).sheet("Data");

  const pts = []; // { year, month, cape }
  for (const r of rows) {
    const dateCell = r?.[COL_DATE];
    const cape = r?.[COL_CAPE];
    if (typeof dateCell !== "number" || dateCell < 1870 || dateCell > 2100) continue;
    if (typeof cape !== "number" || cape <= 0 || !isFinite(cape)) continue;
    // Shiller encodes dates as YYYY.MM decimals (1881.01 = Jan 1881, 1881.1 =
    // Oct 1881): month = fractional part × 100. The +1e-6 guards against float
    // representation error (e.g. 1881.9999…) flooring to the wrong year.
    const year = Math.floor(dateCell + 1e-6);
    const month = Math.round((dateCell - year) * 100);
    if (month < 1 || month > 12) continue;
    pts.push({ year, month, cape: Math.round(cape * 100) / 100 });
  }

  const start = pts[0];
  const end = pts[pts.length - 1];
  const current = end.cape;

  const sorted = pts.map((p) => p.cape).sort((a, b) => a - b);
  const mean = sorted.reduce((a, b) => a + b, 0) / sorted.length;
  const median =
    sorted.length % 2
      ? sorted[(sorted.length - 1) / 2]
      : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2;
  const min = pts.reduce((a, b) => (b.cape < a.cape ? b : a));
  const max = pts.reduce((a, b) => (b.cape > a.cape ? b : a));
  const atOrBelow = sorted.filter((v) => v <= current).length;
  const percentile = (atOrBelow / sorted.length) * 100;

  const out = {
    source: "Robert J. Shiller, Irrational Exuberance data (ie_data.xls), Yale University.",
    citation: "Shiller, R. J. — Cyclically Adjusted Price-Earnings Ratio (CAPE / P/E10).",
    startYear: start.year,
    startMonth: start.month,
    endYear: end.year,
    endMonth: end.month,
    current,
    mean: Math.round(mean * 100) / 100,
    median: Math.round(median * 100) / 100,
    min: { year: min.year, month: min.month, cape: min.cape },
    max: { year: max.year, month: max.month, cape: max.cape },
    percentile: Math.round(percentile * 10) / 10,
    cape: pts.map((p) => p.cape),
  };
  writeFileSync(OUT, render(out));

  console.log(
    `shiller-cape: ${pts.length} monthly CAPE values, ` +
      `${start.year}.${String(start.month).padStart(2, "0")}–${end.year}.${String(end.month).padStart(2, "0")}\n` +
      `  current ${current} · mean ${out.mean} · median ${out.median} · ` +
      `min ${min.cape} (${min.year}) · max ${max.cape} (${max.year}) · ${out.percentile}th pct\n  → ${OUT}`
  );
}

function render(o) {
  const nums = o.cape.map(String);
  const lines = [];
  for (let i = 0; i < nums.length; i += 12) lines.push("    " + nums.slice(i, i + 12).join(", ") + ",");

  return `// AUTO-GENERATED by scripts/reduce-cape.mjs — DO NOT EDIT.
// Re-run: npm run data:cape
//
// Shiller's Cyclically Adjusted P/E ratio (CAPE / P/E10): real S&P price over
// the trailing 10-year average of real earnings. \`cape[i]\` is the value for the
// (i+1)-th month starting at { startYear, startMonth }, consecutive and monthly.

export interface CapeExtreme {
  year: number;
  month: number;
  cape: number;
}

export interface ShillerCape {
  source: string;
  citation: string;
  startYear: number;
  startMonth: number;
  endYear: number;
  endMonth: number;
  /** Most recent CAPE value. */
  current: number;
  /** Long-run average and median over the whole history. */
  mean: number;
  median: number;
  min: CapeExtreme;
  max: CapeExtreme;
  /** Where the current value ranks in the full monthly history (0–100). */
  percentile: number;
  /** Consecutive monthly CAPE values from the start date. */
  cape: number[];
}

export const shillerCape: ShillerCape = {
  source: ${JSON.stringify(o.source)},
  citation: ${JSON.stringify(o.citation)},
  startYear: ${o.startYear},
  startMonth: ${o.startMonth},
  endYear: ${o.endYear},
  endMonth: ${o.endMonth},
  current: ${o.current},
  mean: ${o.mean},
  median: ${o.median},
  min: ${JSON.stringify(o.min)},
  max: ${JSON.stringify(o.max)},
  percentile: ${o.percentile},
  cape: [
${lines.join("\n")}
  ],
};
`;
}

main();
